apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portnyagin-certificate
spec:
  dnsNames:
  - 'portnyagin.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: portnyagin-cert