apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portnyagin-namespace
images:
  - name: nginx
    newName: nginx
    newTag: 1.23.2-alpine
  - name: sunrise9871dock/sampleapp
    newTag:  main



resources:
- ../../base
- ingress.yaml
- namespace.yaml
- certificate.yaml